### ISSUE TITLE
Simple commands do not work with onkyo TX-NR636

### ISSUE THREAD

**Issue by cyberic99** [mikerodrigues/onkyo_eiscp_ruby#8]
It seems that  the new models are more strict regarding the header parsing.
see here:
https://github.com/paulianttila/openhab/commit/31cfe657903f44d3808d28fdac1be3c5ebc0bd68

When I send a PWRQSTN to my TX-NR636, I get this:
```
$ ./onkyo.rb PWRQSTN
/home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/message.rb:60:in 'initialize': No value specified. (RuntimeError)
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/parser/iscp_parser.rb:23:in 'new'
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/parser/iscp_parser.rb:23:in 'parse'
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/parser.rb:16:in 'parse'
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/receiver.rb:164:in 'send_recv'
	from ./onkyo.rb:149:in '<main>'
```

**Comment by mikerodrigues** [comment]
Thanks for bringing this to my attention. It looks like I just need to add 3 to the current calculation. I've made the change in the 'development' branch. Care to give it a try? I only have an old TX-NR609. I didn't look at the eISCP docs for this, I am sort of guessing based on the linked code.

**Comment by cyberic99** [comment]
That was a quick reply!

Unfortunately, I still get the same error.

However, I have found a working application here:
https://github.com/cljk/jEISCP

the eiscp protocol seems to be handled here:
https://github.com/cljk/jEISCP/blob/master/src/main/java/de/csmp/jeiscp/EiscpProtocolHelper.java

There si a small gui

I was able to send a power off/power on, and I made a capture.

Does it help?
(just rename the file)

![on_off pcapng](https://cloud.githubusercontent.com/assets/193917/6587748/8445a51e-c788-11e4-8a24-f2c49d2ea82f.jpg)

**Comment by mikerodrigues** [comment]
I can't see the image. I  am looking at the data size as specified in headers from messages sent to me from the stereo (presumably Onkyo got it right) and it looks like it's the number of characters in the Command and the Parameter, plus 5. For example, the PWR01 I get back after a PWRQSTN has a data size of 10.

If you got what you need that's cool, but I'd still like to fix this issue in case other people are using it. There are a lot of options for Onkyo/eISCP control libraries/apps out there though.

**Comment by cyberic99** [comment]
click on on_off.pcapng link, and save as a pcapng file. you can then open it in wireshark.
In fact, I do not really got what I need, because I would like to avoid java if I can...
I would prefer a solution based on ruby.
Plus, your monitoring mode is great.
I have looked at other libraries, and almost all of them have not been updated for a while, and are based on the same incorrect implementation of the specification ;-(

I can do more tests if you want

**Comment by mikerodrigues** [comment]
I submitted another commit to development. I would try it before reading this so if I'm wrong you'll know beforehand.

Sorry, I was in a hurry and spaced on your comment about the pcap. I looked at it and it looks like in both instances, the Data Size in the header is equal to 9. It looks like these are coming from your computer though? My gem would have a size of 7, and my onkyo sends PWR01 with a size of 10, which is what the development version is set to now.

We have:

Start: "!" - 1 character
Unit type: "1" - 1 character
Command: "PWR" - 3 characters
Parameter: "00" - 2 characters

Total: 7 characters, which is how v2.0.0 of this gem counts.

The discrepancy must be coming from the end characters which can be:
           
       "[EOF]" or "[EOF][CR]" or "[EOF][CR][LF]" depend on model

According to the documentation for ISCP.

My library sends 2 control characters at the end that aren't accounted for in the count ( 0d and 0a):

           Special Characters
      [CR] Carriage Return ASCII Code 0x0D
      [LF] Line Feed ASCII Code 0x0A
      [EOF] End of File ASCII Code 0x1A

Hopefully as long as messages are consistent it will work and we won't have to determine the model before appending end characters.

Thanks for the info and I'm glad you like monitoring mode. You might also checkout 'hifi', there's a fork in my repo but I'm not the original author. It's not done but if you're interested in Ruby and you use the NET playback on your stereo alot it might be cool.

**Comment by cyberic99** [comment]
Hello again

I have made a quick patch to iscp_parser.rb to print the amp answers:


-        Message.new(**hash)
+        print(string.gsub(/[^[:print:]]/,'.'))
+       print(" | ")
+        print(string.bytes.to_a.map { |n| "%02x" % n }.join(" "))
+        a = Message.new(**hash)
+       print("\n")
+       a

Maybe you could add a command line flag to see the content of the packets?
I get this:

$ ./onkyo.rb PWR01
!1ECNTX-NR636/60128/XX/0009B0D3E931... | 21 31 45 43 4e 54 58 2d 4e 52 36 33 36 2f 36 30 31 32 38 2f 58 58 2f 30 30 30 39 42 30 44 33 45 39 33 31 19 0d 0a
PWR01 | 50 57 52 30 31
!1NLT0101000000280100FF0100My Favorites... | 21 31 4e 4c 54 30 31 30 31 30 30 30 30 30 30 32 38 30 31 30 30 46 46 30 31 30 30 4d 79 20 46 61 76 6f 72 69 74 65 73 1a 0d 0a
!1NLSC0P... | 21 31 4e 4c 53 43 30 50 1a 0d 0a
!1NLSU0-nectarine... | 21 31 4e 4c 53 55 30 2d 6e 65 63 74 61 72 69 6e 65 1a 0d 0a
!1NLSU1----... | 21 31 4e 4c 53 55 31 2d 2d 2d 2d 1a 0d 0a
!1NLSU2----... | 21 31 4e 4c 53 55 32 2d 2d 2d 2d 1a 0d 0a
!1NLSU3----... | 21 31 4e 4c 53 55 33 2d 2d 2d 2d 1a 0d 0a
!1NLSU4----... | 21 31 4e 4c 53 55 34 2d 2d 2d 2d 1a 0d 0a
!1NLSU5----... | 21 31 4e 4c 53 55 35 2d 2d 2d 2d 1a 0d 0a
PWR | 50 57 52/home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/message.rb:60:in `initialize': No value specified. (RuntimeError)
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/parser/iscp_parser.rb:26:in `new'
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/parser/iscp_parser.rb:26:in `parse'
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/parser.rb:16:in `parse'
	from /home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/receiver.rb:164:in `send_recv'
	from ./onkyo.rb:149:in `<main>'

I don' t understand where the 'PWR' comes from
And the NLS command seems to be unknown

the network capture is included, both ways now ;-)
.36 is the amp, and .10 is my computer

I will try to contribute better than that, after this crash is solved

Thanks
Eric
![cap2 pcapng](https://cloud.githubusercontent.com/assets/193917/6606587/df46cfa0-c838-11e4-8440-80634a1cf08a.png)

**Comment by mikerodrigues** [comment]
I compared your pcaps to mine, I see the same pattern for ending characters on message sent from the receiver. This gem is only sending '0d'

discovery replies: 0d 0a

regular replies: 1a 0d 0a

I push a commit to development that uses these terminator sequences.

I have been thinking about adding a debug mode to get raw packet information.

I'm not sure what you mean by "where the 'PWR' comes from".

The NLS command has to do with listing the number of menu items on the screen IIRC. It looks like you're browsing the favorites menu or something.

**Comment by mikerodrigues** [comment]
If you want to get byte-arrays you can use #to_eiscp on a Message object with #bytes:
 
    message_object.to_eiscp.to_bytes

**Comment by mikerodrigues** [comment]
I probably should have tested this first, I think I can't send regular messages now. Discovery works okay though.

**Comment by cyberic99** [comment]
About the NLS command, I am not browsing the favorites, but the amp send it on power on, it seems.

The question about the PWR was that it seems we receive a 'PWR' message from the amp, right?
is it normal? without the exclamation mark?

I understand this is not easy for you to debug this way...

If you are still interested in handling these new models/commands, and if you want me to do more tests, or captures, tell me

Thanks

**Comment by mikerodrigues** [comment]
If you have your stereo hooked up to a TV you'll probably see your Favorites on-screen. NLS is supported and is in the yaml file. It's Net-USB-List-Info. I'm pretty sure that "hifi" gem ignores it outright.

the PWR command is the "System Power" command. The stereo sends PWR01 in response to your PWRQSTN, so it would seem it is working unless that message was sent when you turned it on with the button or the physical remote. The "01" is the command parameter (I refer to it as 'value' in the gem but I'm thinking about changing the name to match the official spec), it just means that "System Power" is set to "On".

Each command will make the receiver send a response. The response will be the new value/parameter for whatever command you send. So:

Sending PWRQSTN returns PWR01 if your system is on.

Sending PWR00 will return PWR00 because the command puts the system into "Standby".

Sending MVLUP (Master volume level-up) will return MVL23 where 23 is a hex representation of the new volume level.

Did the changes to the terminator work for you?

**Comment by mikerodrigues** [comment]
Here's a PDF that describes the protocol: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0CDAQFjAC&url=http%3A%2F%2Fwww.ip-symcon.de%2Fforum%2Fattachment.php%3Fattachmentid%3D22957%26d%3D1379923904&ei=izcCVYr5AdatyASft4EY&usg=AFQjCNHRJnY9MkX7Af_DLOSjgzIoRzCRYA&sig2=rLpa6EbIHEjch5pZgVRv5Q&bvm=bv.88198703,d.aWw

**Comment by mikerodrigues** [comment]
I guess it's in the yaml file but it's not parsed like the others.

**Comment by mikerodrigues** [comment]
I just looked at the Onkyo Android App's packets using tcpdump on my router. They only end with \x0d\x0a so I just pushed another commit. It fixed sending for me.

**Comment by cyberic99** [comment]
Ok I will try the new code ASAP.
My question was about this line:
```
PWR | 50 57 52/home/eric/.gem/ruby/2.2.0/gems/onkyo_eiscp_ruby-2.0.0/lib/eiscp/message.rb:60:in `initialize': No value specified. (RuntimeError)
```
Is the 'PWR' answer unexpected?

**Comment by mikerodrigues** [comment]
Can you show me what code you ran to get that error? The error you got indicates that an attempt at instantiating a Message object failed because no 'value' was specified. The "PWR" string lacks a value, so the error makes sense in this context.

The Parser probably didn't find a 'value' in the string it was given. This could have been a string you gave it, or data off the network from the receiver.

**Comment by cyberic99** [comment]
The code I run is simply that:
```
$ ./onkyo.rb PWR01
```

**Comment by mikerodrigues** [comment]
If you run that while the stereo is turned off, does it turn on?

Have you enabled HDMI pass-through on the receiver so that it will accept commands when it is in Standby?

**Comment by cyberic99** [comment]
It seems that the cause of all these backtraces and parsing errors were that my amp was in a strange state. I unplugged then replugged it, and now everything works flawlessly, thanks!


FYI, HDMI pass through and "network during standby" are different options.

Thanks a lot for your support.

**Comment by mikerodrigues** [comment]
That makes sense, as that response looked truncated. I've seen my Onkyo wig out and require a restart every once in a while too.

The terminator characters were in fact wrong, so you inadvertently discovered something that needed to be fixed anyways.

Thanks for helping me improve the gem. Feel free to open another issue if you come across a problem in the future. I'm glad it's working for you.
